name: GitHub metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: "master"}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📊 Get Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: JustinLung

          template: classic
          base: activity, repositories, metadata

          plugin_languages: yes
          plugin_lines: yes